module.exports = {
  categories: [
    {
      id: "cml75jb5k0002loixejfjazva",
      name: "Recepción de Sábado",
      description: "Recursos para la recepción y bienvenida del sábado.",
      iconKey: "star",
      iconColor: "#f59e0b",
      imageUrl: null,
      isActive: true,
    },
    {
      id: "cml75l2uk0003loix1puqf64x",
      name: "Puesta de Sol",
      description: "Programa espiritual, ambiente de adoración",
      iconKey: "heart",
      iconColor: "#fb923c",
      imageUrl: null,
      isActive: true,
    },
    {
      id: "cml75ly650004loix7jwfd6sr",
      name: "Mayordomía en 5 Minutos",
      description: "Es contenido corto, basado en tiempo ⏱️",
      iconKey: "clock",
      iconColor: "#3b82f6",
      imageUrl: null,
      isActive: true,
    },
    {
      id: "cml75n8qz0006loixo6rvzyzh",
      name: "24h de Mayordomía",
      description: "Evento continuo de tiempo",
      iconKey: "clock",
      iconColor: "#8b5cf6",
      imageUrl: null,
      isActive: true,
    },
    {
      id: "cml75nsrh0007loixoqhkggus",
      name: "Revive 2026",
      description: "Evento grande, impacto general 🌍",
      iconKey: "heart",
      iconColor: "#ef4444",
      imageUrl: null,
      isActive: true,
    },
    {
      id: "cml75octa0008loixtkswmiqo",
      name: "Arte, intros y otros",
      description: "Es material audiovisual 🎬",
      iconKey: "video",
      iconColor: "#ec4899",
      imageUrl: null,
      isActive: true,
    },
    {
      id: "cml75ouzh0009loixdcfo6z85",
      name: "Lanzamiento Revive 2026",
      description: "Conecta con materiales oficiales 🔗",
      iconKey: "link",
      iconColor: "#1e3a8a",
      imageUrl: null,
      isActive: true,
    },
    {
      id: "cml763qta000floixwi6859aw",
      name: "Buen Siervo Fiel",
      description:
        "Espacio de mayordomía de 5 minutos desarrollado en la Escuela Sabática.",
      iconKey: "star",
      iconColor: "#22c55e",
      imageUrl: null,
      isActive: true,
    },
  ],

  items: [
    {
      id: "cml75tx3v000aloixomy5z5r5",
      categoryId: "cml75jb5k0002loixejfjazva",
      type: "ONEDRIVE",
      title: "30 Ene | A Dios toda honra (PDF)",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Meditación en PDF para la recepción de sábado en familia.",
      iconKey: "book",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml75whzy000bloixbndrst8x",
      categoryId: "cml75jb5k0002loixejfjazva",
      type: "ONEDRIVE",
      title: "Audio | A Dios toda honra",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Versión en audio de la meditación.",
      iconKey: "music",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml75x958000cloixh0zqyetu",
      categoryId: "cml75jb5k0002loixejfjazva",
      type: "ONEDRIVE",
      title: "Imágenes para redes sociales | Enero",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Paquete de imágenes para redes sociales.",
      iconKey: "folder",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml75zmhs000dloixchkxakdn",
      categoryId: "cml75jb5k0002loixejfjazva",
      type: "YOUTUBE",
      title: "Libre en Cristo | 31 enero",
      url: "https://www.youtube.com/watch?v=cBbqQj5Skg4",
      description: "Programa Probad y Ved.",
      iconKey: "video",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml760g88000eloixb0argqi7",
      categoryId: "cml75jb5k0002loixejfjazva",
      type: "YOUTUBE",
      title: "Dios bendice a su manera",
      url: "https://www.youtube.com/watch?v=PvS08l8ILhA",
      description: "Programa Video Primero Dios.",
      iconKey: "video",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml764hpx000gloix419bivcd",
      categoryId: "cml763qta000floixwi6859aw",
      type: "ONEDRIVE",
      title: "Remedios Naturales 1 PDF",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Material de mayordomía sobre remedios naturales.",
      iconKey: "book",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml764z1o000hloixnupwreiu",
      categoryId: "cml763qta000floixwi6859aw",
      type: "ONEDRIVE",
      title: "Remedios Naturales 2 PDF",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Segunda parte de remedios naturales.",
      iconKey: "book",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml765jko000iloixfpgk9ju8",
      categoryId: "cml763qta000floixwi6859aw",
      type: "ONEDRIVE",
      title: "Ejercicio físico | PDF",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Tema de mayordomía relacionado con el cuidado del cuerpo.",
      iconKey: "book",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml766oni000jloixkr47mfy3",
      categoryId: "cml763qta000floixwi6859aw",
      type: "ONEDRIVE",
      title: "Comunión personal | PDF",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Reflexión sobre la comunión diaria.",
      iconKey: "book",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml7678me000kloixalvaoj9t",
      categoryId: "cml763qta000floixwi6859aw",
      type: "ONEDRIVE",
      title: "Culto familiar | PDF",
      url: "https://mailadventistas-my.sharepoint.com/",
      description: "Guía sobre la práctica del culto familiar.",
      iconKey: "book",
      iconColor: "#3b82f6",
      isActive: true,
    },
    {
      id: "cml7690od000lloixzr5o5mvd",
      categoryId: "cml763qta000floixwi6859aw",
      type: "YOUTUBE",
      title: "Fortaleciendo la adoración a Dios",
      url: "https://www.youtube.com/watch?v=gLRdBHB8IiQ",
      description: "Video sobre adoración en el culto familiar.",
      iconKey: "video",
      iconColor: "#3b82f6",
      isActive: true,
    },
  ],
};
